---
title: "4.4 Relationship between Minecraft Buildings and Creative Thinking"
output: html_notebook
---

```{r}
# 匯入實驗資料
data <- read.csv("C:/Users/David/Desktop/Designing_Creative_Sandbox_Games/Data_Analysis/Raw_Data/實驗資料.csv", stringsAsFactors = TRUE)
```

### **Intercorrelation of Minecraft Building Facets**

```{r}
# 提取兩組樣本的資料並分別儲存
flow <- data[data$Experimental_Condition == "心流", ]
basic <- data[data$Experimental_Condition == "原始", ]
```

```{r}
# 觀察兩組樣本的建築整體創意分布
mean(flow$Overall_Creativity)
sd(flow$Overall_Creativity)
mean(basic$Overall_Creativity)
sd(basic$Overall_Creativity)

qqnorm(flow$Overall_Creativity)
qqline(flow$Overall_Creativity)
qqnorm(basic$Overall_Creativity)
qqline(basic$Overall_Creativity)
```

```{r}
# 檢驗兩組樣本的建築整體創意是否為常態分布（YES/NO）
shapiro.test(flow$Overall_Creativity)
shapiro.test(basic$Overall_Creativity)
```

```{r}
# 觀察兩組樣本的建築適當性分布
mean(flow$Appropriateness)
sd(flow$Appropriateness)
mean(basic$Appropriateness)
sd(basic$Appropriateness)

qqnorm(flow$Appropriateness)
qqline(flow$Appropriateness)
qqnorm(basic$Appropriateness)
qqline(basic$Appropriateness)
```

```{r}
# 檢驗兩組樣本的建築適當性是否為常態分布（YES/NO）
shapiro.test(flow$Appropriateness)
shapiro.test(basic$Appropriateness)
```

```{r}
# 觀察兩組樣本的建築獨創性分布
mean(flow$Originality)
sd(flow$Originality)
mean(basic$Originality)
sd(basic$Originality)

qqnorm(flow$Originality)
qqline(flow$Originality)
qqnorm(basic$Originality)
qqline(basic$Originality)
```

```{r}
# 檢驗兩組樣本的建築獨創性是否為常態分布（YES）
shapiro.test(flow$Originality)
shapiro.test(basic$Originality)
```

```{r}
# 觀察兩組樣本的建築美感分布
mean(flow$Aesthetics)
sd(flow$Aesthetics)
mean(basic$Aesthetics)
sd(basic$Aesthetics)

qqnorm(flow$Aesthetics)
qqline(flow$Aesthetics)
qqnorm(basic$Aesthetics)
qqline(basic$Aesthetics)
```

```{r}
# 檢驗兩組樣本的建築美感是否為常態分布（YES）
shapiro.test(flow$Aesthetics)
shapiro.test(basic$Aesthetics)
```

```{r}
# 觀察兩組樣本的建築驚喜感分布
mean(flow$Surprise)
sd(flow$Surprise)
mean(basic$Surprise)
sd(basic$Surprise)

qqnorm(flow$Surprise)
qqline(flow$Surprise)
qqnorm(basic$Surprise)
qqline(basic$Surprise)
```

```{r}
# 檢驗兩組樣本的建築驚喜感是否為常態分布（YES/NO）
shapiro.test(flow$Surprise)
shapiro.test(basic$Surprise)
```

```{r}
# 觀察兩組樣本的建築精細度分布
mean(flow$Elaboration)
sd(flow$Elaboration)
mean(basic$Elaboration)
sd(basic$Elaboration)

qqnorm(flow$Elaboration)
qqline(flow$Elaboration)
qqnorm(basic$Elaboration)
qqline(basic$Elaboration)
```

```{r}
# 檢驗兩組樣本的建築精細度是否為常態分布（YES/NO）
shapiro.test(flow$Elaboration)
shapiro.test(basic$Elaboration)
```

```{r}
# 針對心流組的資料，檢驗 Minecraft 建築的各項創意指標間是否有相關性
library(psych)
print(corTest(data[data$Experimental_Condition == "心流", 35:40], method = "spearman")$stars, quote = FALSE)
```

```{r}
# 針對原始組的資料，檢驗 Minecraft 建築的各項創意指標間是否有相關性
print(corTest(data[data$Experimental_Condition == "原始", 35:40], method = "spearman")$stars, quote = FALSE)
```

### **Divergent Thinking**

#### **Fluency**

```{r}
# 針對心流組的資料，檢驗實驗前的發散思維流暢性與 Minecraft 建築創意是否有相關性（NO）
cor.test(flow$AUT_Fluency_Pretest, flow$Overall_Creativity, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Fluency_Pretest, flow$Appropriateness, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Fluency_Pretest, flow$Originality, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Fluency_Pretest, flow$Aesthetics, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Fluency_Pretest, flow$Surprise, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Fluency_Pretest, flow$Elaboration, alternative = "two.sided", method = "spearman")
```

```{r}
# 針對原始組的資料，檢驗實驗前的發散思維流暢性與 Minecraft 建築創意是否有相關性（NO）
cor.test(basic$AUT_Fluency_Pretest, basic$Overall_Creativity, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Fluency_Pretest, basic$Appropriateness, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Fluency_Pretest, basic$Originality, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Fluency_Pretest, basic$Aesthetics, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Fluency_Pretest, basic$Surprise, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Fluency_Pretest, basic$Elaboration, alternative = "two.sided", method = "spearman")
```

#### **Originality**

```{r}
# 針對心流組的資料，檢驗實驗前的發散思維獨創性與 Minecraft 建築創意是否有相關性（NO）
cor.test(flow$AUT_Originality_Pretest, flow$Overall_Creativity, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Originality_Pretest, flow$Appropriateness, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Originality_Pretest, flow$Originality, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Originality_Pretest, flow$Aesthetics, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Originality_Pretest, flow$Surprise, alternative = "two.sided", method = "spearman")
cor.test(flow$AUT_Originality_Pretest, flow$Elaboration, alternative = "two.sided", method = "spearman")
```

```{r}
# 針對原始組的資料，檢驗實驗前的發散思維獨創性與 Minecraft 建築創意是否有相關性（除了美感之外的每一項都有）
cor.test(basic$AUT_Originality_Pretest, basic$Overall_Creativity, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Originality_Pretest, basic$Appropriateness, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Originality_Pretest, basic$Originality, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Originality_Pretest, basic$Aesthetics, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Originality_Pretest, basic$Surprise, alternative = "two.sided", method = "spearman")
cor.test(basic$AUT_Originality_Pretest, basic$Elaboration, alternative = "two.sided", method = "spearman")
```

### **Convergent Thinking**

```{r}
# 針對心流組的資料，檢驗實驗前的收斂思維能力與 Minecraft 建築創意是否有相關性（NO）
cor.test(flow$RAT_Pretest, flow$Overall_Creativity, alternative = "two.sided", method = "spearman")
cor.test(flow$RAT_Pretest, flow$Appropriateness, alternative = "two.sided", method = "spearman")
cor.test(flow$RAT_Pretest, flow$Originality, alternative = "two.sided", method = "spearman")
cor.test(flow$RAT_Pretest, flow$Aesthetics, alternative = "two.sided", method = "spearman")
cor.test(flow$RAT_Pretest, flow$Surprise, alternative = "two.sided", method = "spearman")
cor.test(flow$RAT_Pretest, flow$Elaboration, alternative = "two.sided", method = "spearman")
```

```{r}
# 針對原始組的資料，檢驗實驗前的收斂思維能力與 Minecraft 建築創意是否有相關性（NO）
cor.test(basic$RAT_Pretest, basic$Overall_Creativity, alternative = "two.sided", method = "spearman")
cor.test(basic$RAT_Pretest, basic$Appropriateness, alternative = "two.sided", method = "spearman")
cor.test(basic$RAT_Pretest, basic$Originality, alternative = "two.sided", method = "spearman")
cor.test(basic$RAT_Pretest, basic$Aesthetics, alternative = "two.sided", method = "spearman")
cor.test(basic$RAT_Pretest, basic$Surprise, alternative = "two.sided", method = "spearman")
cor.test(basic$RAT_Pretest, basic$Elaboration, alternative = "two.sided", method = "spearman")
```
